import type { Metadata } from 'next';
import { Michroma, Questrial } from 'next/font/google';
import { Footer } from './components/layout/Footer';
import { Header } from './components/layout/Header';
import './globals.css';
import SmoothScrollProvider from './providers/SmoothScrollProvider';

const michroma = Michroma({
  subsets: ['latin'],
  variable: '--font-michroma',
  weight: '400',
});

const questrial = Questrial({
  subsets: ['latin'],
  variable: '--font-questrial',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${michroma.variable} ${questrial.variable} antialiased`}
      >
        <Header />
        <SmoothScrollProvider>
          <main>{children}</main>
          <Footer />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
